[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 25

decorations = "Transparent"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "ComicShannsMono Nerd Font"

size = 14