---
- name: Install Alacritty via Homebrew
  hosts: localhost
  become: false

  tasks:
    - name: Install Dockutil
      homebrew:
        name: dockutil
        state: present

    - name: Install Alacritty
      homebrew:
        name: alacritty
        state: present

    - name: Check if Alacritty is already in the Dock
      shell: dockutil --list | grep -q "/Applications/Alacritty.app"
      register: alacritty_present_on_dock
      ignore_errors: true

    - name: Add Alacritty to the Dock if not present
      shell: dockutil --add "/Applications/Alacritty.app"
      when: alacritty_present_on_dock.rc != 0



    - name: Install Visual Studio Code
      homebrew:
        name: visual-studio-code
        state: present
    
    - name: Check if Visual Studio Code is already in the Dock
      shell: dockutil --list | grep -q "/Applications/Visual%20Studio%20Code.app/"
      register: vscode_present_on_dock
      ignore_errors: true

    - name: Add Visual Studio Code to the Dock if not present
      shell: dockutil --add "/Applications/Visual Studio Code.app"
      when: vscode_present_on_dock.rc != 0

    - name: Install Docker
      homebrew:
        name: docker
        state: present

    - name: Install Postman
      homebrew:
        name: postman
        state: present
    
    - name: Check if Postman is already in the Dock
      shell: dockutil --list | grep -q "Postman.app"
      register: postman_present_on_dock
      ignore_errors: true

    - name: Add Postman to the Dock if not present
      shell: dockutil --add "/Applications/Postman.app"
      when: postman_present_on_dock.rc != 0

    - name: Install Slack
      homebrew:
        name: slack
        state: present

    - name: Check if Slack is already in the Dock
      shell: dockutil --list | grep -q "Slack.app"
      register: slack_present_on_dock
      ignore_errors: true

    - name: Add Slack to the Dock if not present
      shell: dockutil --add "/Applications/Slack.app"
      when: slack_present_on_dock.rc != 0
    
    - name: Install Google Chrome
      homebrew:
        name: google-chrome
        state: present

    - name: Check if Google Chrome is already in the Dock
      shell: dockutil --list | grep -q "Chrome.app"
      register: chrome_present_on_dock
      ignore_errors: true

    - name: Add Google Chrome to the Dock if not present
      shell: dockutil --add "/Applications/Google Chrome.app"
      when: chrome_present_on_dock.rc != 0

    - name: Install Firefox Developer Edition from cask
      homebrew_cask:
        name: firefox@developer-edition
        state: present

    - name: Install Telegram from cask
      homebrew_cask:
        name: telegram
        state: present

    - name: Check if Telegram is already in the Dock
      shell: dockutil --list | grep -q "Telegram.app"
      register: telegram_present_on_dock
      ignore_errors: true

    - name: Add Telegram to the Dock if not present
      shell: dockutil --add "/Applications/Telegram.app"
      when: telegram_present_on_dock.rc != 0

    - name: Check if Oh My Zsh is already installed
      shell: test -d ~/.oh-my-zsh
      register: ohmyzsh_installed
      ignore_errors: true

    - name: Download Oh My Zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install_ohmyzsh.sh
      when: ohmyzsh_installed.rc != 0

    - name: Run Oh My Zsh installation script
      command: sh /tmp/install_ohmyzsh.sh --unattended
      register: ohmyzsh_result
      failed_when: "'FAILED' in ohmyzsh_result.stderr"
      when: ohmyzsh_installed.rc != 0

    - name: install ComicShannsMono Nerd Font from cask
      homebrew_cask:
        name: font-comic-shanns-mono-nerd-font
        state: present

    - name: Install zsh-you-should-use plugin
      git:
        repo: https://github.com/MichaelAquilina/zsh-you-should-use.git
        dest: ~/.oh-my-zsh/custom/plugins/you-should-use

    - name: Install zsh-autosuggestions plugin
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions

    - name: Install tunnelblick from cask
      homebrew_cask:
        name: tunnelblick
        state: present