# Exports
export PATH=/opt/homebrew/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="agnoster"

# Plugins
plugins=(
	colored-man-pages
	docker
	git
	vscode
	you-should-use
	zsh-autosuggestions
)

# End
source $ZSH/oh-my-zsh.sh

# Public Aliases
  # Playgrounds to avoid installing languages
  alias pgnode='docker run -it -v "$(pwd):/tmp"  -w "/tmp" node:23  sh'
  alias pgruby='docker run -it -v "$(pwd):/tmp"  -w "/tmp" ruby:3 sh'
  alias pgpython='docker run -it -v "$(pwd):/tmp"  -w "/tmp" python:3.10 sh'

# Private Aliases
source $HOME/.config/private_aliases.zsh