# Exports
export PATH=/opt/homebrew/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="agnoster"

# Plugins
plugins=(
	colored-man-pages
	docker
	git
	vscode
	you-should-use
	zsh-autosuggestions
)

# End
source $ZSH/oh-my-zsh.sh
