# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Exports
export PATH=/opt/homebrew/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="powerlevel10k/powerlevel10k"

# Plugins
plugins=(
	colored-man-pages
	docker
	docker-compose
	git
	vscode
	you-should-use
	zsh-autosuggestions
)

# End
source $ZSH/oh-my-zsh.sh

# Public Aliases
  # Playgrounds to avoid installing languages
  alias pgnode='[ "$PWD" != "$HOME" ] && docker run -it -v "$(pwd):/tmp" -w "/tmp" node:23 sh || echo "Nope, you are at home"'
  alias pgruby='[ "$PWD" != "$HOME" ] && docker run -it -v "$(pwd):/tmp" -w "/tmp" ruby:3 sh || echo "Nope, you are at home"'
  alias pgpython='[ "$PWD" != "$HOME" ] && docker run -it -v "$(pwd):/tmp"  -w "/tmp" python:3.10 sh || echo "Nope, you are at home"'
  alias pgubuntu='[ "$PWD" != "$HOME" ] && docker run -it -v "$(pwd):/tmp" -w "/tmp" ubuntu:latest sh || echo "Nope, you are at home"'
  alias ctop='docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest'
  alias docker-compose="docker compose"

# Private Aliases
source $HOME/.config/private_aliases.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
